name: Checks

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize]

permissions: {}

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ExodusMovement/actions/setup/yarn-berry@65b395a82884455e8dc0cbc32355d8864f1ec30c
        with:
          npm-token: ${{ secrets.NPM_TOKEN }}
      - name: Install dependencies
        run: yarn install --immutable
      - name: Lint
        run: yarn lint
      - name: Format
        run: yarn format:check
  test:
    name: Test
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - uses: ExodusMovement/actions/setup/yarn-berry@65b395a82884455e8dc0cbc32355d8864f1ec30c
        with:
          npm-token: ${{ secrets.NPM_TOKEN }}
      - name: Install dependencies
        run: yarn install --immutable
      - name: Test
        run: yarn test
      - name: Build
        run: yarn build
