name: Release
on:
  push:
    branches:
      - master

permissions:
  contents: read

jobs:
  publish:
    environment: release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ExodusMovement/actions/setup/yarn-berry@65b395a82884455e8dc0cbc32355d8864f1ec30c
        with:
          npm-token: ${{ secrets.NPM_TOKEN }}
      - name: Install dependencies
        run: yarn install --immutable
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}
        run: yarn semantic-release
